name: park_me
description: Park Anywhere you GO.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  custom_info_window: ^1.0.1
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  flutter_map_location_marker: ^9.1.1
  location: ^7.0.1
  http: ^1.3.0
  flutter_polyline_points: ^2.1.0
  collection: ^1.17.1
  device_info_plus: ^11.3.0
  maplibre: ^0.2.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/parking_spot.svg
    - assets/car.png

flutter_launcher_icons: # hadi d icons
  android: true # platforms
  ios: true
  image_path: "green_back.png"  #icon path
